assignment-8-passFullTest

diff --git a/base_external/rootfs_overlay/etc/init.d/S98lddmodules b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
--- a/base_external/rootfs_overlay/etc/init.d/S98lddmodules
+++ b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
@@ -96,6 +96,40 @@ loadmodule_faulty()
     fi
 }
 
+loadmodule_aesdchar()
+{
+    module="aesdchar"
+    # Use the same name for the device as the name used for the module
+    device="aesdchar"
+    # Support read/write for owner and group, read only for everyone using 644
+    mode="664"
+
+    # Group: since distributions do it differently, look for wheel or use staff
+    # These are groups which correspond to system administrator accounts
+    if grep -q '^staff:' /etc/group; then
+        group="staff"
+    else
+        group="wheel"
+    fi
+
+    echo "Load ${module} module, exit on failure"
+    insmod /lib/modules/$(uname -r)/extra/$module.ko $* || return 1
+    echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
+    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
+    if [ ! -z ${major} ]; then
+        echo "Remove any existing /dev node for /dev/${device}"
+        rm -f /dev/${device}
+        echo "Add a node for our device at /dev/${device} using mknod"
+        mknod /dev/${device} c $major 0
+        echo "Change group owner to ${group}"
+        chgrp $group /dev/${device}
+        echo "Change access mode to ${mode}"
+        chmod $mode  /dev/${device}
+    else
+        echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
+    fi
+}
+
 unloadmodule_scull()
 {
     module="scull"
@@ -127,6 +161,19 @@ unloadmodule_faulty()
     rm -f /dev/${device}
 }
 
+unloadmodule_aesdchar()
+{
+    module="aesdchar"
+    device="aesdchar"
+
+    # invoke rmmod with all arguments we got
+    rmmod $module || return 1
+
+    # Remove stale nodes
+
+    rm -f /dev/${device}
+}
+
 case "$1" in
     start)
         echo "Loading scull driver"
@@ -142,6 +189,13 @@ case "$1" in
             echo "Failed"
             exit 1
         fi
+        
+        echo "Loading aesdchar driver"
+        loadmodule_aesdchar
+        if [ $? -eq 1 ]; then
+            echo "Failed"
+            exit 1
+        fi
 
         echo "Loading hello module with modprobe"
         modprobe hello || exit 1
@@ -150,6 +204,13 @@ case "$1" in
     stop)
         echo "Unloading hello module"
         rmmod hello || exit 1
+        
+        echo "Unloading aesdchar driver"
+        unloadmodule_aesdchar
+        if [ $? -eq 1 ]; then
+            echo "Failed"
+            exit 1
+        fi
         
         echo "Unloading faulty driver"
         unloadmodule_faulty
